name: AI Agent

on:
  issues:
    types:
      - opened

jobs:
  issue:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - name: Show Issue
        run: |
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Title:"
          echo "${{ github.event.issue.title }}"
          echo ""
          echo "Body:"
          echo "${{ github.event.issue.body }}"